import Foundation

public struct TexAssembler: Sendable {
    public init() {}

    public func assembleSemanticDocument(
        project: ResolvedProject,
        chapters: [ChapterSpec]
    ) throws -> AssembledDocument {
        let root = project.root.appendingPathComponent("semantic", isDirectory: true)
        let pagesDirectory = root.appendingPathComponent("pages", isDirectory: true)
        let chaptersDirectory = root.appendingPathComponent("chapters", isDirectory: true)

        try prepareDirectory(root)
        try prepareDirectory(pagesDirectory)
        try prepareDirectory(chaptersDirectory)

        let pageNumbers = chapters.flatMap(\.pageNumbers)
        let selectedSet = Set(pageNumbers)
        let blocksByPage = Dictionary(grouping: project.manifest.blocks.filter { selectedSet.contains($0.page) }) { $0.page }
        let firstPage = pageNumbers.first ?? 1

        var pageTexURLs: [URL] = []
        for pageNumber in pageNumbers {
            let pageRecord = project.manifest.pages[pageNumber - 1]
            let pageBlocks = (blocksByPage[pageNumber] ?? []).sorted { lhs, rhs in
                let lhsTop = lhs.bbox.y + lhs.bbox.height
                let rhsTop = rhs.bbox.y + rhs.bbox.height
                if abs(lhsTop - rhsTop) > 1 {
                    return lhsTop > rhsTop
                }
                return lhs.bbox.x < rhs.bbox.x
            }

            let pageTexURL = pagesDirectory.appendingPathComponent(String(format: "page-%04d.tex", pageNumber))
            let pageSource = renderPageSource(
                pageRecord: pageRecord,
                blocks: pageBlocks
            )
            try pageSource.write(to: pageTexURL, atomically: true, encoding: .utf8)
            pageTexURLs.append(pageTexURL)
        }

        let pageTexByNumber = Dictionary(uniqueKeysWithValues: zip(pageNumbers, pageTexURLs))
        let chapterTexURLs = try chapters.map { chapter -> URL in
            let chapterTexURL = chaptersDirectory.appendingPathComponent("\(chapter.id).tex")
            let chapterSource = renderChapterSource(
                chapter: chapter,
                pageTexURLs: chapter.pageNumbers.compactMap { pageTexByNumber[$0] }
            )
            try chapterSource.write(to: chapterTexURL, atomically: true, encoding: .utf8)
            return chapterTexURL
        }

        let mainTexURL = root.appendingPathComponent("main.tex")
        let pageWidth = project.manifest.pages[firstPage - 1].width
        let pageHeight = project.manifest.pages[firstPage - 1].height
        let mainSource = renderMainSource(
            chapterTexURLs: chapterTexURLs,
            pageWidth: pageWidth,
            pageHeight: pageHeight
        )
        try mainSource.write(to: mainTexURL, atomically: true, encoding: .utf8)

        return AssembledDocument(
            root: root,
            mainTexURL: mainTexURL,
            chapterTexURLs: chapterTexURLs,
            pageTexURLs: pageTexURLs
        )
    }

    private func prepareDirectory(_ url: URL) throws {
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
    }

    private func renderPageSource(pageRecord: PageRecord, blocks: [BlockRecord]) -> String {
        let pageImage = pageRecord.renderedImagePath ?? ""
        let overlays = blocks.compactMap { block -> String? in
            guard block.status == .transcribed, let snippetPath = block.latexPath else {
                return nil
            }

            let x = format(block.bbox.x)
            let yTop = format(pageRecord.height - block.bbox.y - block.bbox.height)
            let width = format(block.bbox.width)
            let height = format(block.bbox.height)
            let path = texEscapedPath(snippetPath)
            return """
            \\SnippetBlock{\(path)}{\(x)}{\(yTop)}{\(width)}{\(height)}
            """
        }.joined(separator: "\n")

        return """
        \\thispagestyle{empty}
        \\null
        \\PageImage{\(texEscapedPath(pageImage))}
        \(overlays)
        \\newpage
        """
    }

    private func renderChapterSource(chapter: ChapterSpec, pageTexURLs: [URL]) -> String {
        let body = pageTexURLs.map { url in
            "\\input{\(texEscapedPath(url.path))}"
        }.joined(separator: "\n")

        return """
        % generated by pdf-to-latex
        % title: \(chapter.title)
        \(body)
        """
    }

    private func renderMainSource(chapterTexURLs: [URL], pageWidth: Double, pageHeight: Double) -> String {
        let width = format(pageWidth)
        let height = format(pageHeight)
        let chapterInputs = chapterTexURLs.map { url in
            "\\input{\\detokenize{\(texEscapedPath(url.path))}}"
        }.joined(separator: "\n")

        return """
        \\documentclass{article}
        \\usepackage[paperwidth=\(width)bp,paperheight=\(height)bp,margin=0bp]{geometry}
        \\usepackage{graphicx}
        \\usepackage[table]{xcolor}
        \\usepackage[absolute,overlay]{textpos}
        \\pagestyle{empty}
        \\setlength{\\parindent}{0pt}
        \\setlength{\\TPHorizModule}{1bp}
        \\setlength{\\TPVertModule}{1bp}
        \\textblockorigin{0bp}{0bp}

        \\newcommand{\\PageImage}[1]{%
          \\begin{textblock*}{\\paperwidth}(0bp,0bp)%
          \\includegraphics[width=\\paperwidth,height=\\paperheight]{\\detokenize{#1}}%
          \\end{textblock*}%
        }

        \\newcommand{\\SnippetBlock}[5]{%
          \\begin{textblock*}{#4bp}(#2bp,#3bp)%
          {%
            \\setlength{\\fboxsep}{0pt}%
            \\colorbox{white}{%
              \\parbox[t][#5bp][t]{#4bp}{%
                \\vspace{0pt}%
                \\input{\\detokenize{#1}}%
              }%
            }%
          }%
          \\end{textblock*}%
        }

        \\begin{document}
        \(chapterInputs)
        \\end{document}
        """
    }

    private func texEscapedPath(_ path: String) -> String {
        path.replacingOccurrences(of: "\\", with: "/")
    }

    private func format(_ value: Double) -> String {
        String(format: "%.2f", value)
    }
}
